apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp-deployment
  labels:
    app: javawebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebapp
        image: ravindranaik1/javawebapp:latest
        ports:
        - containerPort: 8080
